\dileroelt{selem_results/diskorect_dilation_disk.eps}{ok}{0.000}
& 
        \dileroelt{selem_results/diskorect_dilation_stick.eps}{ok}{0.000}
        & 
        \dileroelt{selem_results/diskorect_dilation_cross.eps}{ko}{0.000}
        & 
        \dileroelt{selem_results/mnist_dilation_disk.eps}{ko}{0.000}
        & 
        \dileroelt{selem_results/mnist_dilation_stick.eps}{ok}{0.000}
        & 
        \dileroelt{selem_results/mnist_dilation_cross.eps}{ko}{0.000}
        & 
        \dileroelt{selem_results/inverted_mnist_dilation_disk.eps}{ko}{0.000}
        & 
        \dileroelt{selem_results/inverted_mnist_dilation_stick.eps}{ok}{0.000}
        & 
        \dileroelt{selem_results/inverted_mnist_dilation_cross.eps}{ko}{0.000}
                
        \\       
        \hline
        Erosion $\ero{}{}$
        & 
        \dileroelt{selem_results/diskorect_erosion_disk.eps}{ok}{0.000}
        & 
        \dileroelt{selem_results/diskorect_erosion_stick.eps}{ok}{0.000}
        & 
        \dileroelt{selem_results/diskorect_erosion_cross.eps}{ok}{0.000}
        & 
        \dileroelt{selem_results/mnist_erosion_disk.eps}{ko}{0.000}
        & 
        \dileroelt{selem_results/mnist_erosion_stick.eps}{ok}{0.000}
        & 
        \dileroelt{selem_results/mnist_erosion_cross.eps}{ko}{0.000}
        & 
        \dileroelt{selem_results/inverted_mnist_erosion_disk.eps}{ko}{0.000}
        & 
        \dileroelt{selem_results/inverted_mnist_erosion_stick.eps}{ok}{0.000}
        & 
        \dileroelt{selem_results/inverted_mnist_erosion_cross.eps}{ko}{0.000}
        \\
        \hline
      \end{tabular}

